### PR TITLE
Adds target-snowflake for #21

### LINKED ISSUE #21: Add snowflake target to meltano
Add target-snowflake to the meltano.yml so snowflake can be a target.

### PR DESCRIPTION
**Pull request by dherbst**
Closes #21 

Adds target-snowflake (the meltano variant) with config references to environment variables.

### CODE REVIEW

**Comment by chriscardillo** [comment]
Would we have to create a new entry for each schema target? For example, if we wanted Github data in a Github schema / Slack data in a Slack schema, would two separate Snowflake targets need be defined in `meltano.yml`?

**Comment by dherbst** [comment]
Yes, similar to how https://github.com/CodeForPhilly/cfp-data-pipeline/pull/29 was done.  This PR, #22 was done before #29, so I didn't break it out.   @machow do you want snowflake broken out as well?   We'd have to create separate ELT jobs anyway so airflow can run them.

**Comment by machow** [comment]
@mariekers is setting up snowflake / sending creds--I'll try to add / merge before the meeting tomorrow...

**Comment by machow** [comment]
Ah yeah, @mariekers set up schemas `GITHUB`, `SLACK`, `LADDR`. I'll add the creds now

**Comment by machow** [comment]
Credentials added (all except the SCHEMA). I didn't update the github action to pull them into the .env, but can if it's helpful!

**Comment by dherbst** [comment]
@machow I think you are saying you want the airflow schema to be GITHUB and SLACK?   I'll revise this, then please take a look.

**Comment by dherbst** [comment]
I added the elt jobs as well.

image

**Comment by machow** [comment]
looks perfect! I'll update the github action in this PR to pull in the new env vars, and then merge to staging :)

**Pull request merged**
