### PR TITLE
Put github and slack into separate schemas for #27

### LINKED ISSUE #27: Have taps ingest to separate schemas
Right now our postgres target for the github and slack taps uses the views schema. One challenge for analysts with this is that they'll see a bunch of tables under the views schema, but without a clear way to distinguish the source.

If we dump tap onto its own schema, then analytic engineers can put nicely transformed results onto views.

image

### PR DESCRIPTION
**Pull request by dherbst**
For #27 puts tap_github into views_github and tap-slack into views_slack

For example:

```sql
datawarehouse=# \dt views_github.*
                 List of relations
    Schema    |       Name       | Type  |  Owner   
--------------+------------------+-------+----------
 views_github | assignees        | table | postgres
 views_github | collaborators    | table | postgres
 views_github | contributors     | table | postgres
 views_github | issue_labels     | table | postgres
 views_github | languages        | table | postgres
 views_github | repository       | table | postgres
 views_github | stargazers       | table | postgres
 views_github | team_members     | table | postgres
 views_github | team_memberships | table | postgres
 views_github | teams            | table | postgres
(10 rows)
```

### CODE REVIEW

**Comment by chriscardillo** [comment]
Implementation looks good, though #28 suggests that the work of creating schemas should be moved to its own DAG.

If #20 is merged in, it should be as easy as moving `datawarehouse_setup.py` into its own DAG folder.

**Review by machow — CHANGES_REQUESTED** [review]
@dherbst thanks for submitting! Do you mind if we put them on schemas named something like `tap_github` and `tap_slack`, instead of starting with `views_`? This way, people can put transformed / joined tables for end-analysts under `views_github_<table_name>`.

(alternately, we could use another convention for end-analyst facing tables than `views`?)

Here's an example of two tables I set on views from laddr that clean up column names, and combine the project and tags tables:

image


I'm happy to make the change, merge and deploy!

**Comment by dherbst** [comment]
Sounds good.

**Comment by dherbst** [comment]
Here are the schemas the data will go into:
```sql
datawarehouse=# \dn
    List of schemas
    Name    |  Owner   
------------+----------
 public     | postgres
 tap_github | postgres
 tap_slack  | postgres
 views      | postgres
(4 rows)

```

**Pull request merged**
