### PR TITLE
upgrade to gusty 0.3.1

### PR DESCRIPTION
**Pull request by chriscardillo**
@machow per your request!

### CODE REVIEW

**Comment by machow** [comment]
@chriscardillo I have a folder called slack_db_cache with another folder in it, and it seems this version identifies it as a task. Do you know if this is a regression?

image

See the report_laddr_project_files task, which is generated off a residual folder from the Rmarkdown operator (it has plots stored in it).

image

**Comment by machow** [comment]
Checked against master and it seems to be a regression

**Comment by chriscardillo** [comment]
I wouldn't call it a regression. gusty 0.3.x features full support for task groups, which means that any subfolder within a DAG's folder will be considered to be a task group.

If you want to avoid this behavior, you can start these subfolders with either a `.` or a `_`, e.g. `.slack_db_cache`

**Comment by chriscardillo** [comment]
I also would not advise saving outputs to folders in your DAG folders in general. Instead consider saving theses to maybe an `outputs` folder in your `AIRFLOW_HOME`.

**Comment by machow** [comment]
These output folders are residuals produced by the operators in your example. What's the way forward? Is there a change that needs to be made to the example, or have I adapted the example incorrectly?

**Comment by machow** [comment]
The reality is that the operators from the example will likely produce residual outputs, because rmarkdown::render by default sets the working directory to the file's location.

**Comment by chriscardillo** [comment]
In terms of the [example RmdOperator](https://github.com/CodeForPhilly/cfp-data-pipeline/blob/8552c727ee97b0037176c1d73a339dbda3ee82f4/airflow/operators/rmd_operator.py#L5), this operator deletes any default output rendered. In the gusty demo, no residual output is left behind. The intention of this operator is to render R code without leaving anything behind.

In the case of the slack_db job, I believe what is happening is that the [cache](https://github.com/CodeForPhilly/cfp-data-pipeline/blob/8552c727ee97b0037176c1d73a339dbda3ee82f4/airflow/dags/prototype/slack_db.Rmd#L150) is not being cleaned up after the job runs. If this is the case, I would recommend either deleting the cache after the job runs (within the .Rmd) or renaming that cache to start with a `.` or a `_` if it is something you want to keep around.

From a gusty perspective, patch options would include:

- Adding the option to ignore all subfolders in a DAG folder, so that you can store anything you want in subfolders of the DAG folder 
- Adding the option to ignore subfolders that start/end with some specific characters/strings (e.g. starts with "report" or ends with "cache")

Let me know what you think would be most helpful here.

**Comment by chriscardillo** [comment]
@machow - I've patched gusty 0.3.2 to include an `ignore_subfolders` argument that can either be passed to a DAG's `METADATA.yml` or directly in `create_dag` that will ignore any subfolders in a DAG.

I hope this helps!

**Comment by chriscardillo** [comment]
@machow - is there anything else I can help with to get this PR merged in? :)

**Comment by chriscardillo** [comment]
@machow - gusty bumped to 0.3.3, and `ignore_subfolders` was placed in `dags.py` so that any DAG folder ignores subfolders by default.

**Comment by machow** [comment]
Ah, sorry for the wait--going to merge in first, then test it out, since it seems like it's probably in a good place!

**Pull request merged**
